### ISSUE TITLE
Add contributing.md file for the markdown-previewer and guidelines for hacktoberfest participants

### ISSUE THREAD

**Issue by hirentimbadiya** [hirentimbadiya/Markdown-Previewer#1]
Create a contributing.md file so that every contributer of the project can understand and contribute to this project.

**Comment by SaiAryan1784** [comment]
Hi can i contribute to this issue??
can you assign it to me?

**Comment by VivekBaldha0712** [comment]
I would like to work on this issue

**Comment by hirentimbadiya** [comment]
> Hi can i contribute to this issue?? can you assign it to me?

Thanks for showing interest @SaiAryan1784, i will be adding some more issues tomorrow please contribute to them, as of now i will continue with @VivekBaldha0712 cause he is also part of this project and we need to work on some documentation things.
