### ISSUE TITLE
make section items in center

### ISSUE THREAD

**Issue by hirentimbadiya** [hirentimbadiya/Markdown-Previewer#10]
we have implemented out divs in section i want them to be in center.

so use justify-content: center and align-items: stretch to make it center.

**Current Behaviour :**
![image](https://github.com/hirentimbadiya/Markdown-Previewer/assets/86219935/3ab384e3-3960-4532-9f85-06730b6b4b1e)

**Desired Behaviour :**
![image](https://github.com/hirentimbadiya/Markdown-Previewer/assets/86219935/fe10d617-7d1a-4346-afe0-51f031c328d7)

**Comment by himughanakash** [comment]
Hey! i want to work on this, please assign me this.

**Comment by prince5638** [comment]
Hey, I would like to work on this issue, 
can you assign it to me?

**Comment by hirentimbadiya** [comment]
@himughanakash, i will add more issue by today keep an eye and go through [contributing guidelines](https://github.com/hirentimbadiya/Markdown-Previewer/blob/main/CONTRIBUTING.md), thanks for showing interest.

**Comment by hirentimbadiya** [comment]
@prince5638, complete this issue and raise PR as soon as possible.

**Comment by prince5638** [comment]
> @prince5638, complete this issue and raise PR as soon as possible.

Okay.

**Comment by himughanakash** [comment]
I asked to assign this issue to me first but it's ok.

**Comment by bangadam** [comment]
Hi @hirentimbadiya I want to work on this issue, I'll work on it soon
