### ISSUE TITLE
move script tag after the body ends and also add defer keyword.

### ISSUE THREAD

**Issue by hirentimbadiya** [hirentimbadiya/Markdown-Previewer#11]
- **It's generally a good practice to place your  `<script>`  tags just before the closing `</body>` tag to ensure that your HTML content is loaded before your scripts are executed.** 

- **Add a defer attribute to the `<script>` tag like this.**
 ```bash
<script src="script.js" defer></script>
```

**Comment by brijeshbhikadiya** [comment]
I would like to work on this.

**Comment by hirentimbadiya** [comment]
Go on @brijeshbhikadiya, fix this issue ASAP.

**Comment by prince5638** [comment]
It would be great for me if you could assign this task/issue to me!

**Comment by hirentimbadiya** [comment]
@prince5638, thanks for showing interest keep an eye to issues tab.
