### ISSUE TITLE
Generate Table Of Contents For Contributing .md file

### ISSUE THREAD

**Issue by hirentimbadiya** [hirentimbadiya/Markdown-Previewer#12]
- **generate table of contents for the contributing.md file**
here is file : [contributing.md](https://github.com/hirentimbadiya/Markdown-Previewer/blob/main/CONTRIBUTING.md)

**Comment by prince5638** [comment]
hey, i want to work on this.

**Comment by hirentimbadiya** [comment]
@prince5638, i see you are already working on issue #8, lets assign this issue to other enthusiastic contributer.

**Comment by meetpaladiya44** [comment]
I would love to solve this issue. Can you please assign it to me?

**Comment by RISHIKESHk07** [comment]
hey @hirentimbadiya is this assigned ?,i would like to contribute

**Comment by hirentimbadiya** [comment]
@meetpaladiya44, asked for assignment first so i am going with him, you can solve the issue number: #14, please comment on that issue so i can assign and before you make any changes make sure you go through [contributing.md](https://github.com/hirentimbadiya/Markdown-Previewer/blob/main/CONTRIBUTING.md) file

**Comment by hirentimbadiya** [comment]
@meetpaladiya44, I am unassining this issue and will assign other candidate.

**Comment by hirentimbadiya** [comment]
@malaviya-parth, c an you finish this up ?

**Comment by brijeshbhikadiya** [comment]
I would like to work on this issue.

**Comment by hirentimbadiya** [comment]
@brijeshbhikadiya, there you go.
