### ISSUE TITLE
Suggestion: Add Custom Template for PRs

### ISSUE THREAD

**Issue by malaviya-parth** [hirentimbadiya/Markdown-Previewer#14]
# Problem

Currently, when contributors open pull requests (PRs) in this repository, there is no standardized format or template to follow for their PR descriptions. This can lead to inconsistent information, missing details, and increased friction in the code review process.

# Solution

I propose that we implement a custom template for PRs in this repository. By providing a standardized template, we can achieve several benefits:

**Consistency:** A custom PR template ensures that every PR includes essential information such as the purpose of the change, related issues, and a checklist for reviewers.
**Clarity:** It helps contributors clearly communicate the purpose and impact of their changes, making it easier for reviewers to understand the context.
**Efficiency:** A template can prompt contributors to include necessary details upfront, reducing back-and-forth communication during code reviews.
**Quality:** It encourages contributors to think about tests, documentation, and adherence to coding guidelines.

# Example
### Description

This PR Fixes #[issue-number]

### Changes Made

[Describe the changes made in your PR]

### Screenshots

[If applicable]

### Checklist

- [ ] I have tested the changes.
- [ ] I have updated documentation if necessary.
- [ ] I have assigned this PR to myself.
- [ ] I have added the appropriate labels.

### Related Issues

[Link to related issues or discussions]

# Impact

Implementing a custom PR template would streamline our contribution process and enhance the overall quality of PR submissions. It would benefit both the contributors and the reviewers, making collaboration more efficient.

**Comment by hirentimbadiya** [comment]
@malaviya-parth, yes this is the issues we need to address, thanks for raising this :)

**Comment by RISHIKESHk07** [comment]
hey @hirentimbadiya  i would like contribute

**Comment by hirentimbadiya** [comment]
> hey @hirentimbadiya i would like contribute

you can work on this.

**Comment by hirentimbadiya** [comment]
@RISHIKESHk07 all the steps are described in the issue description, have a read.

**Comment by RISHIKESHk07** [comment]
PULL REQUEST #20
