### ISSUE TITLE
Bug: markdown preview content coming out of card

### ISSUE THREAD

**Issue by bangadam** [hirentimbadiya/Markdown-Previewer#16]
**Describe the bug**
markdown preview content coming out of the card

**To Reproduce**
1. Fill as much markdown code as possible
2. Check the preview card

**Expected behavior**
content not out from card markdown preview

**Screenshots**
<img width="1394" alt="image" src="https://github.com/hirentimbadiya/Markdown-Previewer/assets/18278184/94b86463-8470-4510-bf46-ae3dcdf31589">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave

**Comment by hirentimbadiya** [comment]
@bangadam, thanks for raising this issue, we will fix this issue as soon as possible, are you interested in fixing this issue ?

**Comment by bangadam** [comment]
please assign this task to me

**Comment by himughanakash** [comment]
Assign this task to me, please.

**Comment by hirentimbadiya** [comment]
Assigned to both @himughanakash , @bangada, fix it asap
