### ISSUE TITLE
Code block preview not available

### ISSUE THREAD

**Issue by yr1404** [hirentimbadiya/Markdown-Previewer#19]
**Describe the bug**
Code is not properly displayed in the preview section.

**To Reproduce**
1. Add code contents using backticks \` ` 
2. You can see that code is not properly displayed

**Expected behavior**
A code block should be displayed containg the content inside backticks \` `

**Screenshots**
![image](https://github.com/hirentimbadiya/Markdown-Previewer/assets/106465753/3662da6d-c483-444b-a29c-99bdce57cc6b)  

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser Chrome
 - Version 117

**Comment by yr1404** [comment]
I can try fixing this issue. Can you assign it to me?

**Comment by hirentimbadiya** [comment]
@yr1404, it is a valid issue and i was thinking about it, sure you can fix this issue, make sure you go through the [contributing guidelines](https://github.com/hirentimbadiya/Markdown-Previewer/blob/main/CONTRIBUTING.md) before you start.

**Comment by hirentimbadiya** [comment]
@yr1404, any updates on this issue ?

**Comment by yr1404** [comment]
I'm working on it. I'll share the update by tomorrow evening.
