### ISSUE TITLE
Responsiveness issue

### ISSUE THREAD

**Issue by anshu-ee-21** [hirentimbadiya/Markdown-Previewer#22]
**Problem:**
The current implementation of the cards lacks responsiveness, resulting in inconsistent card display across various devices with different screen widths.

**Expected Behavior:**
The cards should adapt to the available screen width on various devices, including desktops, tablets, and mobile phones.

**Current Behavior:**
The cards do not respond to changes in screen width, causing them to appear overlapped on smaller screens.

**Steps to Reproduce:**

- Open the application on a desktop with a large screen and observe the layout of the cards.
- Resize the browser window to simulate a smaller screen width (e.g., tablet or mobile device).

![Screenshot 2023-10-07 153957](https://github.com/hirentimbadiya/Markdown-Previewer/assets/98543901/233dfa10-62dc-4502-af06-d5ce22e1edbb)
![Screenshot 2023-10-07 154309](https://github.com/hirentimbadiya/Markdown-Previewer/assets/98543901/2e2b55d7-d4c9-472e-92d3-496c81963a24)

**Comment by anshu-ee-21** [comment]
I can try working on this. Can you assign it to me?

**Comment by hirentimbadiya** [comment]
@anshu-ee-21, I don't think that this is the right issue, because most of the devlopers will be using this site from their desktop or laptop, but if you still think that you this is a valid issue and alredy started working on it then i can assign this issue to you!

**Comment by anshu-ee-21** [comment]
The issue persists even in large screen sizes, in the markdown input text area.
Accessing the issue would be beneficial for better user experience.

![Screenshot 2023-10-08 102019](https://github.com/hirentimbadiya/Markdown-Previewer/assets/98543901/d1540417-e236-4717-9b21-9a5481d56307)

I've begun looking into this problem to some extent.

**Comment by hirentimbadiya** [comment]
great, you can fix this problem, @anshu-ee-21

**Comment by hirentimbadiya** [comment]
@anshu-ee-21, what is the update?

**Comment by TusharGagal** [comment]
Please assign this to me i have fixed this bug. I want to work on it under hacktoberfest 2023.

**Comment by anshu-ee-21** [comment]
@hirentimbadiya, the bug has almost been fixed, just a small part is yet to be completed. I'll complete it by today.

![Screenshot 2023-10-09 114029](https://github.com/hirentimbadiya/Markdown-Previewer/assets/98543901/1cc06eb3-cf9c-4995-98de-4d1cce2adacb)
![Screenshot 2023-10-09 113900](https://github.com/hirentimbadiya/Markdown-Previewer/assets/98543901/0a80914c-e5b4-454e-8abd-8894c53adc0f)

**Comment by anshu-ee-21** [comment]
@hirentimbadiya, the bug has been fixed too. Do I raise a PR now?

![Screenshot 2023-10-09 115722](https://github.com/hirentimbadiya/Markdown-Previewer/assets/98543901/d366f16a-56bf-4338-82f9-7d1ed92e145b)

**Comment by anshu-ee-21** [comment]
@hirentimbadiya, Do I raise a PR now?

**Comment by hirentimbadiya** [comment]
@anshu-ee-21 yes raise the PR, we will review it.

**Comment by hirentimbadiya** [comment]
@anshu-ee-21, please raise PR ASAP.
