### ISSUE TITLE
Add border color and box shadow to text-area when it is focused

### ISSUE THREAD

**Issue by hirentimbadiya** [hirentimbadiya/Markdown-Previewer#23]
add styling for text-area when we focus on text-area it should add border color and border radius.

border color should be : #e74c3c 
box shadow should be  :  2px 2px 10px rgba(231, 76, 60, 0.4)

**Desired Solution :**
![image](https://github.com/hirentimbadiya/Markdown-Previewer/assets/86219935/272552d8-47e4-4630-9ccc-e07027fc50cf)

**Comment by VanshSutariya** [comment]
I would like to work on this issue.

**Comment by hirentimbadiya** [comment]
@VanshSutariya, you can fix this issue.

**Comment by Sudhin-star1** [comment]
Hey, I want to contribute too.
How can I get started?

**Comment by hirentimbadiya** [comment]
> Hey, I want to contribute too. How can I get started?

i will be adding more issues keep an eye till then go though **[contributing.md](https://github.com/hirentimbadiya/Markdown-Previewer/blob/main/CONTRIBUTING.md)** file and follow all the steps and set the project locally.
