### ISSUE TITLE
Markdown input area is not Responsive

### ISSUE THREAD

**Issue by TusharGagal** [hirentimbadiya/Markdown-Previewer#27]
**Describe the bug**
The Markdown input area is not responsive preview input area is alright.
on decreasing the size of screen it is going out of section.
![image](https://github.com/hirentimbadiya/Markdown-Previewer/assets/110715565/234e4a11-0119-4d72-b011-39d36eace446)
 
I will fix it please assign me this task.

**Comment by TusharGagal** [comment]
please assign me this task @hirentimbadiya

**Comment by TusharGagal** [comment]
I  have completed this task and please assign me so that i can pull a merge request.

**Comment by hirentimbadiya** [comment]
Other candidate is already working on the similar issue #22

**Comment by TusharGagal** [comment]
Ohh sorry but he has not completed yet i have fixed this issue.

**Comment by hirentimbadiya** [comment]
@TusharGagal, he is working on it.

**Comment by TusharGagal** [comment]
Thank can you raise any new issue
