### ISSUE TITLE
Add favicon in html file

### ISSUE THREAD

**Issue by hirentimbadiya** [hirentimbadiya/Markdown-Previewer#32]
find any relatable favicon for markdown and add that image as a favicon in html file.

**Comment by VanshSutariya** [comment]
I would like to work on this issue.

**Comment by hirentimbadiya** [comment]
@VanshSutariya, thanks for raising your hand, please submit a PR by tomorrow.

**Comment by heisdinesh** [comment]
@hirentimbadiya can i work on this.
