### ISSUE TITLE
Textarea Overlow

### ISSUE THREAD

**Issue by susanhsrestha** [hirentimbadiya/Markdown-Previewer#33]
**Describe the bug**
The textarea field of the Input field overflow from its div.

**To Reproduce**
1. Go to homepage
2. See error

**Screenshots**

![image](https://github.com/hirentimbadiya/Markdown-Previewer/assets/58846347/d879ac89-b438-435d-82dd-5ccad39e879a)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Edge
 - Version: 117

**Additional context**
I have fixed it and working on a PR.

**Comment by susanhsrestha** [comment]
![image](https://github.com/hirentimbadiya/Markdown-Previewer/assets/58846347/bf2154f8-d307-49c6-b6e7-e867fa04ccb2)

This is the fix I came up with.

**Comment by susanhsrestha** [comment]
@hirentimbadiya can you review this?

**Comment by hirentimbadiya** [comment]
@susanhsrestha, this issue is already in progress by other candidate.
