### ISSUE TITLE
increase the height of preview-area and input-area divs such that visible till the page is.

### ISSUE THREAD

**Issue by hirentimbadiya** [hirentimbadiya/Markdown-Previewer#36]
![image](https://github.com/hirentimbadiya/Markdown-Previewer/assets/86219935/8fa1abd1-a29e-44f7-9b44-747cc63d52d2)

**Comment by brijeshbhikadiya** [comment]
I want to work on this issue.

**Comment by hirentimbadiya** [comment]
there you go @brijeshbhikadiya
