### ISSUE TITLE
Add CSS to HTML page

### ISSUE THREAD

**Issue by hirentimbadiya** [hirentimbadiya/Markdown-Previewer#4]
**About Issue :**
add the styling to the page and make all sections center. and row value for text-area is bit higher so decrease it accordingly. i.e. 25 or 20.

**ScreenShot**
![image](https://github.com/hirentimbadiya/Markdown-Previewer/assets/86219935/21748559-e47a-4780-b5a4-9ee086a7e05f)

**Comment by brijeshbhikadiya** [comment]
I would like to work on this issue

**Comment by hirentimbadiya** [comment]
go on @brijeshbhikadiya

**Comment by SurajPrakash24** [comment]
Hey @hirentimbadiya , I would also love to contribute. Can You please Assign to me

**Comment by hirentimbadiya** [comment]
> Hey @hirentimbadiya , I would also love to contribute. Can You please Assign to me

Thanks for showing interest @SurajPrakash24, i will add more issues today you can contribute to them as of now @brijeshbhikadiya is working on this issue.
