### ISSUE TITLE
Update Header UI and Enhance UI/UX in Markdown Previewer Layout

### ISSUE THREAD

**Issue by LakshanRukantha** [hirentimbadiya/Markdown-Previewer#43]
This issue aims to enhance the user interface of the Markdown Previewer repository by updating the Header's UI and making various UI/UX improvements. These changes will help make the Markdown Previewer more visually appealing and user-friendly.

#### Navbar UI Update:

- Design and implement a more modern and visually pleasing header.
- Ensure that the updated header is responsive and looks good on various screen sizes and devices.

#### Dark & Light Mode Button:

- Update the Dark & Light Mode button to include spacing on the left and right.

#### Layout Update:

- Ensure spacing between elements is uniform and visually appealing.
- Review the width of different sections or elements and adjust them to create a balanced, user-friendly layout.

**Comment by hirentimbadiya** [comment]
@LakshanRukantha, please go through contributing.md before you create any PR.

**Comment by Bhavya-Raghuvanshi** [comment]
@LakshanRukantha Please Assign it to me I would like to contribute in it
