### ISSUE TITLE
change headings font family to Poppins.

### ISSUE THREAD

**Issue by hirentimbadiya** [hirentimbadiya/Markdown-Previewer#5]
**please make sure you do all changes in css file.**

**Google Font Link : [poppins](https://fonts.google.com/specimen/Poppins)**

**Comment by Cstrp** [comment]
U can assigned this me

**Comment by fatimashaikh04** [comment]
heyy , i can help you with this

**Comment by hirentimbadiya** [comment]
@Cstrp you can work on this make sure you go through [contributing .md](https://github.com/hirentimbadiya/Markdown-Previewer/blob/main/CONTRIBUTING.md) file before you start.

**Comment by hirentimbadiya** [comment]
@fatimashaikh04, you can find other issues, i will add more issues in this project, thanks for your interest.

**Comment by fatimashaikh04** [comment]
ok

**Comment by Cstrp** [comment]
> @Cstrp you can work on this make sure you go through [contributing .md](https://github.com/hirentimbadiya/Markdown-Previewer/blob/main/CONTRIBUTING.md) file before you start.

okay)
