### ISSUE TITLE
i can update readme file.

### ISSUE THREAD

**Issue by Deepankar1484** [hirentimbadiya/Markdown-Previewer#53]
Hello @hirentimbadiya, I hope u are doing great. 
Hey i can update the README file for you.
Please assign me the work and give me the labels for hacktobeer fest.

**Comment by hirentimbadiya** [comment]
What changes you will make, can you brief about that.

**Comment by Deepankar1484** [comment]
You can assign me and provide me the logo, i will try my best to give you best output.
