### ISSUE TITLE
change readme file introduction

### ISSUE THREAD

**Issue by hirentimbadiya** [hirentimbadiya/Markdown-Previewer#54]
change readme file introduction to this : 
A simple web application that **permits users to input Markdown and instantly view a preview of the formatted text**. This project encompasses **HTML, CSS, and JavaScript**. Novices can focus on designing the input and output layout, while slightly more experienced beginners can implement real-time updating functionalities.

**Comment by bhavymunjani** [comment]
i would like to work on this issue

**Comment by saakshi002** [comment]
Can you assign me this task? @hirentimbadiya
