### ISSUE TITLE
remove comments from the script.js file

### ISSUE THREAD

**Issue by hirentimbadiya** [hirentimbadiya/Markdown-Previewer#55]

**Comment by bhavymunjani** [comment]
i would you like to work on this issue

**Comment by prince5638** [comment]
I am ready to work on this!

**Comment by hirentimbadiya** [comment]
@bhavymunjani go on!!

**Comment by ankitkumar0622** [comment]
Hi @hirentimbadiya can you assign this task to me.

**Comment by Bhavya-Chawla** [comment]
@hirentimbadiya , I've initiated PR #58. Please have a look.
