### ISSUE TITLE
rewrite the 12th point title in contributing.md 

### ISSUE THREAD

**Issue by hirentimbadiya** [hirentimbadiya/Markdown-Previewer#56]
rewrite the 12th point title in contributing.md file to : 
When other developers update the master branch while you're working on your own branch, your branch becomes outdated and lacks the latest content. To get these changes, follow these steps.

**Comment by bhavymunjani** [comment]
i would like to work on this issue

**Comment by prince5638** [comment]
Hey, allow me to go ahead!

**Comment by hirentimbadiya** [comment]
@prince5638 you can fix this.

**Comment by prince5638** [comment]
> @prince5638 you can fix this.

Okay, i am working on this!
