### ISSUE TITLE
Fix: Previewer content overflow

### ISSUE THREAD

**Issue by mrical** [hirentimbadiya/Markdown-Previewer#60]
**Describe the bug**
The content inside the markdown previewer overflows  

**To Reproduce**
1. Go to '[WEBSITE](https://previewer-for-markdown.vercel.app/)'
2. Add content/markdown of good enough size/length on 'Markdown input area'
3. This generated a preview of markdown in the Markdown Preview section
4. See error The Generated preview overflows the preview section

**Expected behavior**
The Generated preview must come under the boundaries of the preview section
<img width="960" alt="chrome_31Km6gY83P" src="https://github.com/hirentimbadiya/Markdown-Previewer/assets/60258119/f1e53c90-59d6-4676-bc08-51131100d920">

**Screenshots**
Content overflows preview section
<img width="960" alt="chrome_nhA81HS0C1" src="https://github.com/hirentimbadiya/Markdown-Previewer/assets/60258119/6caed7e2-ac61-428a-9ab4-94529ffd9f03">

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [22]

**Smartphone (please complete the following information):**
 - Device: []
 - OS: []
 - Browser []
 - Version []

**Additional context**

**Comment by mrical** [comment]
I am sure i can perfectly fix this issue, you can assign this to me

**Comment by hirentimbadiya** [comment]
> I am sure i can perfectly fix this issue, you can assign this to me

go ahead and fix it quickly. @mrical

**Comment by mrical** [comment]
Hello @hirentimbadiya please merge this ASAP to be counted for Hacktoberfest
