### ISSUE TITLE
make markdown input field in center

### ISSUE THREAD

**Issue by VivekBaldha0712** [hirentimbadiya/Markdown-Previewer#8]
**Screenshot/image**
![WhatsApp Image 2023-10-06 at 11 37 37_8750353c](https://github.com/hirentimbadiya/Markdown-Previewer/assets/86009821/f0af095a-0213-443c-a924-56a0f1cdbaeb)

**Comment by VanshSutariya** [comment]
I would like to work on this issue

**Comment by hirentimbadiya** [comment]
@VanshSutariya, you can fix this issue
